title: Je Sian's Awesome Website
author: Je Sian Keith Herman
email: jeseankeith.hisman@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: jsk_herman # DO NOT include the @ character, or else the build will fail!
github_username:  jsk-herman # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
